on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install automake
      - name: Run autoreconf
        run: autoreconf -fi 
      - name: Run configure
        run: ./configure
      - name: Run make
        run: make
      - name: Run tests
        run: make check
      - name : Run make install
        run: make install
